// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyBXFzc_lHi9KZLcO44e0KqqY9X560unI',
    appId: '1:14342942591:android:fba0730494dc00a679744a',
    messagingSenderId: '14342942591',
    projectId: 'furnday-cb69e',
    databaseURL: 'https://furnday-cb69e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furnday-cb69e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXLpl4xvDKF1_XURUT2OUAIapD-Rc11A',
    appId: '1:14342942591:ios:daad6e073532ebd479744a',
    messagingSenderId: '14342942591',
    projectId: 'furnday-cb69e',
    databaseURL: 'https://furnday-cb69e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furnday-cb69e.appspot.com',
    iosClientId: '14342942591-u965ass9p35phoiv7t5kparugrv683pa.apps.googleusercontent.com',
    iosBundleId: 'com.furnday.furnday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpXLpl4xvDKF1_XURUT2OUAIapD-Rc11A',
    appId: '1:14342942591:ios:daad6e073532ebd479744a',
    messagingSenderId: '14342942591',
    projectId: 'furnday-cb69e',
    databaseURL: 'https://furnday-cb69e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furnday-cb69e.appspot.com',
    iosClientId: '14342942591-u965ass9p35phoiv7t5kparugrv683pa.apps.googleusercontent.com',
    iosBundleId: 'com.furnday.furnday',
  );
}
